dcp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from wakemeup.forms import LoginForm

urlpatterns = [
#     path('admin/', admin.site.urls),
    url('^wakemeup/', include('wakemeup.urls', namespace='wakemeup'), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view( # Catch login before default url
            template_name = 'registration/login.html', 
            authentication_form=LoginForm
        )
        , name="login"),
    url(r'^', include('django.contrib.auth.urls')), # Auth views (login, logout, reset password)
    url(r'^.*$', RedirectView.as_view(pattern_name='wakemeup:index')), # Redirect all other URLs to "Wake Me Up" homepage
]

wakemeup/urls.py
from django.conf.urls import url
from . import views

app_name = 'wakemeup' # qualifies url pattern names with 'wakemeup' namespace (i.e. 'wakemeup:create_contract')
urlpatterns = [

    # Index (i.e. /wakemeup)
    url(r'^$', views.index, name="index"),

    # Contract
    url(r'^contract/$', views.list_contract, name="list_contract"),
    url(r'^contract/(?P<contractid>(\d+))/detail$', views.get_contract, name="get_contract"),
    url(r'^contract/(?P<contractid>(\d+|new))$', views.create_contract, name="create_contract"),

    # Admin
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object"), # Object list
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))/(?P<objectid>\d+)$', views.edit_object, name="edit_object"), # Edit object
    url(r'^admin/(?P<objecttype>(school|class|reward))/(?P<objectid>new)$', views.edit_object, name="edit_object"), # New object
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward|contract))/(?P<objectid>\d+)/delete$', views.delete_object, name="delete_object"), # Delete object    

    # General
    url(r'^(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object_general"), # Object list (non-admin)

    url(r'^admin/tools$', views.execute_admintools, name="execute_admintools"),
    url(r'^admin/edit_permissions', views.edit_permissions, name="edit_permissions"),
    url(r'^admin/manage_program', views.manage_program, name="manage_program"),

    # User 
    url(r'^admin/create_user', views.create_user, name="create_user"),
    url(r'^myaccount', views.myaccount, name="myaccount"),

    # Calendar
    url(r'^calendar/', views.get_calendar, name='get_calendar'),

    # Files
    url(r'^files$', views.list_file, name="list_file"),
    url(r'^files/edit/(?P<fileid>(bulk))?$$', views.edit_file, name="edit_file_bulk"),
    url(r'^files/edit/(?P<fileid>(\d+|new))$', views.edit_file, name="edit_file"),
    url(r'^files/download/(?P<fileid>\d+)$', views.get_file, name='get_file'), # File download
    
    # Misc
    url(r'^admin/img/(?P<objecttype>(teacher))/(?P<objectid>\d+)/preview$', views.preview_image, name="preview_image"), # Image preview
    url(r'^about$', views.about, name='about'),
    url(r'^howtoparticipate$', views.howtoparticipate, name='howtoparticipate'),

    # Ajax
    url(r'^ajax/load-classes/', views.load_classes, name='ajax_load_classes'),
    url(r'^ajax/load-teachers/', views.load_teachers, name='ajax_load_teachers'),
    url(r'^ajax/load-rewards/', views.load_rewards, name='ajax_load_rewards'),
    
    url(r'^ajax/manage-user-display/', views.manage_user_display, name='ajax_manage_user_display'),
    url(r'^ajax/addreward/', views.addreward, name='ajax_add_reward'),

    # Default (catch all)    
    url(r'.*', views.index, name="default"),
]

wakemeup/models/base.py
from django.db import models

class MyModel(models.Model):

    class Meta:
        managed = False
        abstract = True
    
    def save(self, *args, **kwargs):
        return type(self).objects.save(self, *args, **kwargs)
    
    def delete(self):
        return type(self).objects.delete(self)

class Object():
    pass

wakemeup/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse
from django.core.validators import validate_email
from django.core.mail import send_mail
from django.forms.models import formset_factory

from lib.UsefulFunctions.imgUtils import renderImageFromDb
from lib.UsefulFunctions.dateUtils import *
from lib.UsefulFunctions.dataUtils import *
from lib.UsefulFunctions.httpUtils import *
from lib.UsefulFunctions.miscUtils import get_school_year
from lib.UsefulFunctions.stringUtils import *
from lib.UsefulFunctions.fileUtils import get_file_name_info
from lib.UsefulFunctions.googleUtils import GoogleDrive, GoogleCalendar

from django_tables2 import RequestConfig

import psycopg2
import re

from wakemeup.tables import *
from wakemeup.forms import *
from wakemeup.models.school import *
from wakemeup.models.program import *
from wakemeup.models.environment import *
from user.models.user import UserReputationEvent, UserBadge, UserNotification
from user.models.authorization import *

DEFAULT_SCHOOL_YEAR = get_school_year()

# Check authentication (logged in)
def check_authentication(view):
    
    def view_wrapper(*args, **kwargs):
        myuser = args[0].user

        # Check user is logged on
        if myuser.is_authenticated:
            return view(*args, **kwargs)
        else:
            return redirect('login')
        
    return view_wrapper

# Check authorization (logged in & permissions)
def check_authorization(view):
    
    def view_wrapper(*args, **kwargs):
        myuser = args[0].user

        # Check user is logged on
        if myuser.is_authenticated:
            
            # Parse out view info
            viewname = view.__name__ # i.e. "create_contract"
            viewname_split = viewname.split("_")
            
            # Get action & object
            view_action = viewname_split[0]
            view_object = viewname_split[1] if len(viewname_split) > 1 else None # Use second index of view name (if specified)
    
            # Convert to access levels
            if view_action == "list":
                myrequestedaccesslevel = 1
                
            elif view_action == "get":
                myrequestedaccesslevel = 4
                
            elif view_action in ("edit", "execute"):
                if kwargs.get('objectid') == "new":
                    myrequestedaccesslevel = 10 # Create
                else:
                    myrequestedaccesslevel = 8 # Edit
                    
            elif view_action in ("create", "manage"):
                myrequestedaccesslevel = 10
                
            elif view_action == "delete":
                myrequestedaccesslevel = 12
                
            else:
                myrequestedaccesslevel = 1 # Browse
            
            # Get object
            if view_action in ('list','get','edit','create','execute','delete','manage'):
                myobject = Object.objects.get_object_by_name(objectname=kwargs.get('objecttype') or view_object) # business object
            else:
                myobject = Object.objects.get_object_by_name(objectname=viewname) # view

            # Check valid object
            if myobject:

                # Check user has requested access to object
                if myuser.check_access(objectid=myobject.objectid, objectclass=myobject.objectclass, requestedaccesslevel=myrequestedaccesslevel):

                    # Valid permission - continue
                    return view(*args, **kwargs)
        else:
            # Not authenticated - redirect to login page
            return redirect(reverse('login') + '?next={0}'.format(args[0].get_full_path_info()))
        
        # Not authorized - redirect to homepage (TO-DO: Create "not authorized" page)
        return redirect_home()

    # Return view
    return view_wrapper

# Get relative root directory for files
def get_rootdir(request, gd_locator, programname='incentive', ignoreadminflag=False, **kwargs): # TO-DO: Fix hardcoded
    if (request.user.is_admin() and not ignoreadminflag):
        gd_locator = get_gd_locator('programs_base')
        programname = None
        
    return File.objects.lookup_fileid_gd(gd_locator=gd_locator, programname=programname, **kwargs)

# Check if form is being saved
def check_saveform(request):
    return True if request.method == "POST" and not request.POST.get('source') else False

# AJAX Request handler
def load_teachers(request):
    contractid = request.GET.get('contractid') # Check if existing contract

    # Determine which teachers to display
    # If existing contract, use contract teacheruserid
    if(contractid):
        teacheruserid = Contract.objects.get(contractid=contractid).teacheruserid
    # If logged on user is a teacher teacheruserid
    elif(request.user.usertype == 'TR'):
        teacheruserid = request.user.userid
    # Otherwise, return all teachers
    else:
        teacheruserid = None
    
    # Lookup teacher classes
    teachers = Teacher.objects.get_teachers(teacheruserid = teacheruserid)
    
    return render(request, 'wakemeup/admin/menus/teacher_options.html', {'teachers': teachers, 'teacheruserid':teacheruserid})

def load_classes(request):
    contractid = request.GET.get('contractid') # Check for existing contract
    schoolid = request.GET.get('schoolid') # Check for existing school
    teacheruserid = request.GET.get('teacheruserid') # Check selected teacher

    classid = None

    # If existing contract, use existing data
    if(contractid):
        mycontract = Contract.objects.get(contractid=contractid)
        classid = mycontract.classid
        teacheruserid = mycontract.teacheruserid

        classes = Class.objects.get_classes(classid=classid, teacheruserid = teacheruserid)
        
    elif(schoolid):
        classes = Class.objects.get_classes(schoolid=schoolid)
        
    # Lookup teacher classes
    elif (teacheruserid):
        
        # If id = 0, include all teachers (used for add user form)
        if str(teacheruserid) == "0":
            teacheruserid = None
            
        classes = Class.objects.get_classes(teacheruserid = teacheruserid)
        
    else:
        classes = [] # Return empty list (create contract form)

    return render(request, 'wakemeup/admin/menus/class_options.html', {'classes': classes, 'classid': classid})

def load_rewards(request):
    contractid = request.GET.get('contractid') # Check if existing contract
    userid = request.user.userid

    # Get all existing rewards for given goal
    if(contractid):
        selectedrewards = ContractPartyReward.objects.get_contract_party_rewards(contractid=contractid)        
        selectedrewards = [myreward.rewardid for myreward in selectedrewards]
        
    else:
        selectedrewards = []

    context = {
        'selectedrewards': selectedrewards
    }
    
    return render(request, 'wakemeup/admin//reward_options.html', context)

@check_authorization
def execute_admintools(request):

    # Handle link redirect
    if check_saveform(request):
        action = request.POST.get('action')
        
        if action == "drivesync":
            gd = GoogleDrive()
            gd.sync()
            
    return HttpResponse("Success")

def manage_user_display(request):
    actiontype = request.GET.get('actiontype') # Check if existing contract

    # Load notifications
    if(actiontype == 'loadnotifications'):
        mynotifications = UserNotification.objects.get_notifications(userid=request.user.userid,activeonlyflag=False,maxrows=10)

        return render(request, 'wakemeup/notifications.html', {'usernotifications': mynotifications})

    # Set notifications as "seen"
    elif(actiontype == "clearusernotifications"):
        notificationtype = request.GET.get('notificationtype')
        get_user_model()(userid=request.user.userid).manage_display_info(actiontype='clearusernotifications',notificationtype=notificationtype)
        
    # Set notifications as "seen"
    elif(actiontype == "clearnewrepnotification"):
        get_user_model()(userid=request.user.userid).manage_display_info(actiontype='clearnewrepnotification')
        
    return HttpResponse()

# View to display images from DB
def preview_image(request, objecttype, objectid):
    if(objecttype == 'teacher'):
        img = Teacher.objects.get(objectid).defaultsignaturescanfile

    if(img):
        return renderImageFromDb(img)
    else:
        return HttpResponse()

def redirect_home():
    return redirect('wakemeup:index')        

def redirect_referer(request):
    return redirect(request.META['HTTP_REFERER']) if request.META.get('HTTP_REFERER') else redirect_home()

@check_authorization
def delete_object(request, objecttype, objectid):
    
    # Set default redirect
    if(objecttype == 'contract'):        
        myredirect = redirect('wakemeup:list_contract')
    else:
        myredirect = redirect('wakemeup:list_object', objecttype = objecttype)
        
    if(request.method == 'POST'):
        if(objecttype == 'contract'):
            myobject = Contract.objects.get(objectid)

            # Send notification when deleting non-draft contracts
            if myobject.contractstatus != 'D':
                sendnotifications = True
            else:
                sendnotifications = False

            # Delete contract
            myobject.delete(sendnotifications=sendnotifications)

            # Send notifications
            if(sendnotifications):
                myobject.send_emails(
                    email_subject = 'Duitama Colegio Project - Contrato (#' + str(myobject.contractid) + ') ha sido eliminado',
                    email_body = 'Se elimin' + mychr('o') + ' su contrato (#' + str(myobject.contractid) + ')'
                )
        else:

            if(objecttype == 'school'):
                myobject = School.objects.get(objectid)
                

wakemeup/templates/wakemeup/admin/fields/avatar.html
{% load static %}
{% if record.profilepicturefilepath %}
<img src="{% static 'img/avatar/'|add:record.profilepicturefilepath|add:record.profilepicturefilename %}" height="32px"></img>
{% else %}
--
{% endif %}

wakemeup/templates/wakemeup/admin/fields/badge.html
{% if record.badgelevel == "B" %}
<i class="fas fa-certificate" style="color:#CD7F32" title="Bronce"></i>
{% elif record.badgelevel == "S" %}
<i class="fas fa-medal" style="color:silver" title="Plata"></i>
{% elif record.badgelevel == "G" %}
<i class="fas fa-trophy" style="color:gold" title="Oro"></i>
{% endif %}

wakemeup/templates/wakemeup/admin/fields/contract_buttons.html
<div class="text-nowrap">
	<!-- Teacher/admin buttons -->
	{% if request.user.usertype == "TR" and request.user.userid == record.teacheruserid or request.user.is_admin %}
		{% if not record.revisionapprovalts %}
			{% if record.contractstatus == "D" or record.contractstatus == "P" %}
				{% if record.contractstatus == "D" or record.partyapprovalcount == 0 %}
					<!-- EDIT -->
					<form style="display:inline-block" action="{% url 'wakemeup:create_contract' contractid=record.contractid %}" method="post">
					    {% csrf_token %}
						<input class="btn {{ displayinfo.buttonsize }} btn-primary" name="submit_other" type="submit" value="Editar"/>
					</form>
				{% else %}
					{% if displayinfo.displaytextflag %}
						<i>No se puede editar ya que<br>ya se aprob&#243; por {{ record.partyapprovalcount }} persona{{record.partyapprovalcount|pluralize:",s"}}</i><br><br>
					{% endif %}
				{% endif %}
				<!-- DELETE -->
				<form style="display:inline-block" action="{% url 'wakemeup:delete_object' objecttype=objecttype objectid=record.contractid %}" method="post">
				    {% csrf_token %}
					<input class="btn {{ displayinfo.buttonsize }} btn-warning cancel_confirm" name="delete" type="submit" value="Borrar"/>
				</form>
			{% endif %}
		{% endif %}
		{% if record.contractstatus in "A,R,P,E" %}
			{% if not record.revisioneligibilityflag and record.contractstatus in "A,R" %}
				{% if displayinfo.displaytextflag %}
					<br><br>
					{% if record.revisionapprovalts %}
						<i>Ya se modific&#243; el contrato<br>({{ record.revisionapprovalts|date }})</i>
					{% else %}
						<i>Ya pas&#243; la fecha tope para<br>modificar el contrato<br>({{record.revisiondeadlinets|date}})</i>
					{% endif %}
				{% endif %}
			{% endif %}		
		{% endif %}
		{% if record.contractfinalizationts and displayinfo.displaytextflag %}
			<i>Ya se finaliz&#243; el contrato<br>({{ record.contractfinalizationts|date }})</i><br>
		{% endif %}
	{% endif %}
	
	<!-- Student buttons -->	
	{% if request.user.usertype == "ST" %}
		<!-- VOTE -->
		{% if record.contractstatus in "P,A" %}
			<!-- Restrict to party user or group leader -->
			{% for party in record.partyuserinfo.currentparties %}
				{% if request.user.userid == party.partyuserid or request.user.userid == party.groupinfo.leaderuserid or request.user.is_admin %}
					{% if party.partyapprovalts %}
						<i>Ya se acept&#243;<br>({{ party.partyapprovalts }})</i>
					{% elif record.contractstatus == "P" %}
						<a class="btn {{ displayinfo.buttonsize }} btn-primary" href="{% url 'wakemeup:get_contract' contractid=record.contractid %}#participants" >Aceptar</a>
					{% endif %}<br><br>
				{% endif %}
			{% endfor %}

		<!-- FEEDBACK -->
		{% elif record.contractstatus in "E,F" %}
			<!-- Restrict to party user or group users -->
			{% for party in record.partyuserinfo.currentparties %}
				{% if request.user.userid == party.partyuserid or request.user.userid in party.groupuseridlist %}
					<!-- Display button if user accepted and has not evaluated yet -->
					{% if party.partyapprovalts %}
						{% if not party.evaluationts %}
							<form style="display:inline-block">
							    {% csrf_token %}
							    <input type="hidden" name="contractid" value="{{ record.contractid }}" />
							    <input type="hidden" name="partyuserid" value="{{ request.user.userid }}" />
								<input type="submit" class="btn btn-xs btn-success" name="submit_partyevaluation" id="submit_{{ request.user.userid }}" value="Evaluar"/>
							</form><br>
						{% else %}
							<i>Ya se evalu&#243; el contrato<br>({{ party.evaluationts }})</i><br>
						{% endif %}
					{% endif %}
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endif %}
</div>

wakemeup/templates/wakemeup/admin/fields/contract_goals.html
{% load static %}

{% for goal in record.goalinfo.currentgoals %}
	{% if record.contractapprovalts and goal.acceptedflag or not record.contractapprovalts %}
		<div>
			<span class="text-nowrap">
				<span>
					<strong>
						Opci&#243;n 
						{% if goal.difficultylevel == "E" %} F&#225;cil
						{% elif goal.difficultylevel == "M" %} Media
						{% elif goal.difficultylevel == "D" %} Dif&#237;cil
						{% endif %}
					</strong>
				</span>
	
				<span style="vertical-align:middle">
					{% if goal.acceptedflag %} 
						<i class="fas fa-check-circle" style="color:#9ACD32;font-size:1.25em"></i>
					{% endif %}
				</span>				
			</span>

			<div>
				<i>{{ goal.goaldescription }}</i><br>
				{% include "wakemeup/contract/include/rewardoptions.html" %}
			</div>
		</div>
		<br>
	{% endif %}
{% endfor %}

wakemeup/templates/wakemeup/admin/fields/currency_field.html
{% load humanize %}
{% if value is not None %}
	${{value|intcomma}}
{% else %}
	<span class="text-danger"><i>Pendiente</i></span>
{% endif %}

wakemeup/templates/wakemeup/admin/fields/db_file.html
{% if record.datausepolicyfileid %}
	<a href="{% url 'wakemeup:download_file_fromdb' fileid=record.datausepolicyfileid %}"><i class="fas fa-file-download faicon"></i></a>
{% else %}
	--
{% endif %}

wakemeup/templates/wakemeup/admin/fields/display_image.html
{% if record.defaultsignaturescanfile %}
<img src="{% url 'wakemeup:preview_image' objecttype=objecttype objectid=value %}" alt="">
{% endif %}

wakemeup/templates/wakemeup/admin/fields/experiencerating.html
<label for="id_highperformers" class="col-form-label col-sm-5">
    Experiencia con el/la docente
</label>
<div class="controls col-sm-7">
	<fieldset class="rating">
		{% with '5 4 3 2 1' as my_array %}
			{% for myrating in my_array.split %}
				<input 
					type="radio" 
					id="id_form-{{forloop.parentloop.parentloop.counter0}}-star{{myrating}}" 
					name="form-{{forloop.parentloop.parentloop.counter0}}-experiencerating" 
					value="{{myrating}}" 
					{% if field.value == myrating|add:"0" %}checked{% endif %}
				/>
				<label 
					class = "full" 
					for="id_form-{{forloop.parentloop.parentloop.counter0}}-star{{myrating}}" 
					title="{{myrating}} estrellas">
				</label>
			{% endfor %}
		{% endwith %}
	</fieldset>
</div>

wakemeup/templates/wakemeup/admin/fields/guardian_policy.html
{% if record.guardianapprovalpolicy.requiredfields %}
	<div class="text-nowrap">
		{% for field in record.guardianapprovalpolicy.requiredfields %}- 
			{% if field == "idfullname" %}Nombre de tutor
			{% elif field == "idnumber" %}Numero de cedula
			{% elif field == "idissuelocation" %}Lugar de expedici&#243;n
			{% elif field == "idissuedate" %}Fecha de expedici&#243;n
			{% endif %}<br>
		{% endfor %}
	</ul>
{% else %}
	--
{% endif %}

wakemeup/templates/wakemeup/admin/fields/manage_buttons.html
<div class="text-nowrap">
	<!-- Hide buttons for global rewards -->
	{% if not record.rewardid or not record.globalflag or user.is_superuser %}
		<form action="{% url 'wakemeup:edit_object' objecttype=objecttype objectid=value %}" method="post" style="display:inline-block" >
		    {% csrf_token %}
			<input class="btn btn-sm btn-primary" name="submit_other" type="submit" value="Editar" />
		</form>
		<!-- Hide "Delete" link in "Edit class" view -->
		{% if not record.classid or user.is_superuser %}
			<form action="{% url 'wakemeup:delete_object' objecttype=objecttype objectid=value %}" method="post" style="display:inline-block" >
			    {% csrf_token %}
				<input class="btn btn-sm btn-warning" name="delete" type="submit" value="Borrar" onclick="return confirm('\u00BFEst\u00E1 seguro que desee eliminar este objeto?');"/>
			</form>
		{% endif %}
	{% endif %}
</div>

wakemeup/templates/wakemeup/admin/fields/rewardtype.html
{% if record.globalflag %}
	Com&#250;n
{% else %}
	Personal
{% endif %}

wakemeup/templates/wakemeup/admin/fields/teacher_classes.html
{% if value.classid %}
  <a href="{% url 'wakemeup:edit_object' objecttype='class' objectid=value.classid %}">{{ value.classdisplayname }}</a><br> 
{% else %}
  {% for myrow in value %} 
    <a href="{% url 'wakemeup:edit_object' objecttype='class' objectid=myrow.classid %}">{{ myrow.classdisplayname }}</a><br> 
  {% endfor %}
{% endif %}

wakemeup/templates/wakemeup/admin/fields/user_groups.html
{% load static %}
{% for user in record.groupuserinfo %}
	<span class="text-nowrap
	{% if record.leaderuserid == user.userid %} font-weight-bold font-italic {% endif %}
	">
		{{ user.fullname }}
		<br>
	</span>
{% endfor %}

wakemeup/templates/wakemeup/admin/fields/usergroup_buttons.html
<div class="text-nowrap">
	<form action="" method="post" name="userGroupForm_{{ value }}" style="display:inline-block">{% csrf_token %}
		<input type="button" class="btn btn-xs btn-primary" name="submit_usergroup" id="submit_{{ value }}" value="Editar"/>
		<input type="hidden" name="groupuserid" value="{{ value }}" />
		<input type="hidden" name="classid" value="{{ record.classid }}" />
	</form>
	<form action="{% url 'wakemeup:delete_object' objecttype='usergroup' objectid=value %}" method="post" style="display:inline-block" >
	    {% csrf_token %}
		<input class="btn btn-xs btn-warning" name="delete" type="submit" value="Borrar" onclick="return confirm('\u00BFEst\u00E1 seguro que desee eliminar este objeto?');"/>
	</form>
</div>