dcp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from wakemeup.forms import LoginForm

urlpatterns = [
#     path('admin/', admin.site.urls),
    url('^wakemeup/', include('wakemeup.urls', namespace='wakemeup'), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view( # Catch login before default url
            template_name = 'registration/login.html', 
            authentication_form=LoginForm
        )
        , name="login"),
    url(r'^', include('django.contrib.auth.urls')), # Auth views (login, logout, reset password)
    url(r'^.*$', RedirectView.as_view(pattern_name='wakemeup:index')), # Redirect all other URLs to "Wake Me Up" homepage
]

wakemeup/urls.py
from django.conf.urls import url
from . import views

app_name = 'wakemeup' # qualifies url pattern names with 'wakemeup' namespace (i.e. 'wakemeup:create_contract')
urlpatterns = [

    # Index (i.e. /wakemeup)
    url(r'^$', views.index, name="index"),

    # Contract
    url(r'^contract/$', views.list_contract, name="list_contract"),
    url(r'^contract/(?P<contractid>(\d+))/detail$', views.get_contract, name="get_contract"),
    url(r'^contract/(?P<contractid>(\d+|new))$', views.create_contract, name="create_contract"),

    # Admin
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object"), # Object list
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))/(?P<objectid>\d+)$', views.edit_object, name="edit_object"), # Edit object
    url(r'^admin/(?P<objecttype>(school|class|reward))/(?P<objectid>new)$', views.edit_object, name="edit_object"), # New object
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward|contract))/(?P<objectid>\d+)/delete$', views.delete_object, name="delete_object"), # Delete object    

    # General
    url(r'^(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object_general"), # Object list (non-admin)

    url(r'^admin/tools$', views.execute_admintools, name="execute_admintools"),
    url(r'^admin/edit_permissions', views.edit_permissions, name="edit_permissions"),
    url(r'^admin/manage_program', views.manage_program, name="manage_program"),

    # User 
    url(r'^admin/create_user', views.create_user, name="create_user"),
    url(r'^myaccount', views.myaccount, name="myaccount"),

    # Calendar
    url(r'^calendar/', views.get_calendar, name='get_calendar'),

    # Files
    url(r'^files$', views.list_file, name="list_file"),
    url(r'^files/edit/(?P<fileid>(bulk))?$$', views.edit_file, name="edit_file_bulk"),
    url(r'^files/edit/(?P<fileid>(\d+|new))$', views.edit_file, name="edit_file"),
    url(r'^files/download/(?P<fileid>\d+)$', views.get_file, name='get_file'), # File download
    
    # Misc
    url(r'^admin/img/(?P<objecttype>(teacher))/(?P<objectid>\d+)/preview$', views.preview_image, name="preview_image"), # Image preview
    url(r'^about$', views.about, name='about'),
    url(r'^howtoparticipate$', views.howtoparticipate, name='howtoparticipate'),

    # Ajax
    url(r'^ajax/load-classes/', views.load_classes, name='ajax_load_classes'),
    url(r'^ajax/load-teachers/', views.load_teachers, name='ajax_load_teachers'),
    url(r'^ajax/load-rewards/', views.load_rewards, name='ajax_load_rewards'),
    
    url(r'^ajax/manage-user-display/', views.manage_user_display, name='ajax_manage_user_display'),
    url(r'^ajax/addreward/', views.addreward, name='ajax_add_reward'),

    # Default (catch all)    
    url(r'.*', views.index, name="default"),
]

wakemeup/models/base.py
from django.db import models

class MyModel(models.Model):

    class Meta:
        managed = False
        abstract = True
    
    def save(self, *args, **kwargs):
        return type(self).objects.save(self, *args, **kwargs)
    
    def delete(self):
        return type(self).objects.delete(self)

class Object():
    pass

wakemeup/models/environment.py
# Model field names must match database column names for "Raw" queries to match fields properly
from django.db import models
from wakemeup.models.base import MyModel
from lib.UsefulFunctions.dbUtils import *
from lib.UsefulFunctions.stringUtils import mychr, split_filename
from lib.UsefulFunctions.dataUtils import generate_options, to_json, to_array
import lib.UsefulFunctions.googleUtils as google
from django.contrib.postgres.fields import JSONField

import copy

class FileManager(models.Manager):
    def all(self):
        return self.get_files()

    def get(self, fileid):
        return get_data_pk(self, 'SP_DCPGetFile(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)', (to_array(fileid), None, None, None, None, None, None, None, None, None))

    def get_files(self, fileid=None, fileclass=None, filecategory=None, alternatefileid=None, contractid=None, schoolid=None, schoolyear=None, fileattributes=None, filesource=None, accessinfo=None, hierarchyflag=False, relativeroot=None, orderbyhierarchyflag=True):
        
        fileid = to_array(fileid)
        filecategory = to_array(filecategory)
        
        if not hierarchyflag:
            return get_data(self, 'SP_DCPGetFile(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)', (fileid, fileclass, filecategory, alternatefileid, contractid, schoolid, schoolyear, fileattributes, filesource, to_json(accessinfo)))
        else:
            return get_data(self, 'SP_DCPGetFileHierarchy(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)', (fileid, fileclass, filecategory, alternatefileid, contractid, schoolid, schoolyear, fileattributes, filesource, to_json(accessinfo), relativeroot, orderbyhierarchyflag))

    def get_file_alt(self, fileid, filesource='GD'):
        result = self.get_files(alternatefileid=fileid, filesource=filesource)
        
        return result[0] if result else None

    def lookup_fileid(self, gd_locator=None, programname=None, userid=None, fileattributes={}, alternatefileidflag=False, **kwargs):
        
        # Initialize new dictionary
        newattributes = copy.deepcopy(fileattributes)

        for myvar in ('gd_locator','programname','userid'):
            if eval(myvar):
                newattributes[myvar] = str(eval(myvar)) # GD returns properties as string (TO-DO: Check this)

        myfile = self.get_files(filesource='GD', fileattributes=to_json(newattributes), **kwargs)

        if myfile:
            return myfile[0].alternatefileid if alternatefileidflag else myfile[0].fileid # Return alternate id for first result

    def lookup_fileid_gd(self, **kwargs):
        return self.lookup_fileid(alternatefileidflag=True, **kwargs)

    def save(self, myFile, *args, **kwargs):

        # Extract gd_file info if it exists
        gd_file = kwargs.get('gd_file')

        # Save file to google drive first (if defined)
        if gd_file:

            # Extract google drive connection
            gd = gd_file.pop('gd')

            # Save additional properties
            gd_file['metadata'].setdefault('properties',{}).update(myFile.get_properties(altproperties=gd_file['metadata'].get('properties')))

            # Save file
            gd_file = gd.create_file(**gd_file)

            # Prepare file
            gd.prepare_gd_file(gd_file)

            # Update original File attributes
            myFile.filename = gd_file.get('name')
            myFile.fileextension = gd_file.get('fileExtension')
            myFile.filesize = gd_file.get('size')
            myFile.filetype = gd_file.get('mimeType')
            myFile.filedescription = myFile.filedescription or gd_file.get('description') # Give priority to original value
            myFile.filesource = 'GD'
            myFile.alternatefileid = gd_file.get('id')
            myFile.fileattributes = to_json(gd_file['properties'])
            myFile.fileURL = myFile.fileURL or gd_file.get('webContentLink')
            myFile.schoolid = myFile.schoolid or gd_file['properties'].get('schoolid') # Give priority to original value
            myFile.schoolyear = myFile.schoolyear or gd_file['properties'].get('schoolyear') # Give priority to original value

        # Save to repository
        fileid = save_data('SP_DCPUpsertFile',
            (
                myFile.fileid,
                myFile.filename,
                myFile.fileextension,
                myFile.filesize,
                myFile.filetype,
                myFile.filedescription,
                myFile.filesource,
                myFile.filedata,
                myFile.fileURL,
                myFile.filepath,
                myFile.fileclass,
                myFile.filecategory,
                myFile.fileattributes,
                myFile.alternatefileid,
                myFile.contractid,
                myFile.schoolid,
                myFile.schoolyear
            )
         )[0]

        return {'fileid':fileid,'gd_file':gd_file}
    
    def save_batch(self, fileinfo, filesource=None, overridecustomfieldsflag=None, deleteoptions={'deleteremovedflag':False}):
        return save_data('SP_DCPUpsertFileBatch', (to_json(fileinfo), filesource, to_json(deleteoptions), overridecustomfieldsflag), returnall=True)
    
    def update_attributes(self, fileid, fileinfo=None, acllist=None, updategdflag=True):
        fileid = to_array(fileid)
        result = save_data('SP_DCPUpdateFileAttributes', (fileid, to_json(fileinfo), to_json(acllist)))
        
        # Update Google Drive info
        if (fileid and updategdflag):
            
            # Connect to Google Drive
            gd = google.GoogleDrive(permissions=['all'])
            
            # Get list of GD files with info
            myfiles = self.get_files(fileid=fileid, filesource='GD')
            
            # Update google attributes
            for myfile in myfiles:
                gd.update_file(fileid=myfile.alternatefileid, metadata={'properties':myfile.get_properties()})
        
        return result
    
    def delete(self, myFile, contractid=None, schoolid=None, alternatefileid=None, filesource=None):
        return delete_data('SP_DCPDeleteFile', (myFile.fileid, myFile.contractid, myFile.schoolid, myFile.alternatefileid, myFile.filesource))
            
class CategoryManager(models.Manager):
    def all(self):
        return self.get_categories()
    
    def get(self, categoryclass, categorytype):
        return get_data_pk(self, 'SP_DCPGetCategory(%s,%s)', (categoryclass, categorytype))
    
    def get_categories(self, categoryclass = None, categorytype = None):
        return get_data(self, 'SP_DCPGetCategory(%s,%s)', (categoryclass, categorytype))
    
    def get_category_options(self, categoryclass = None, categorytype = None):

        return generate_options(
            items = self.get_categories(categoryclass=categoryclass, categorytype=categorytype), 
            idfield = "categorytype", 
            displayfield = "categorydisplayname"
        )

class File(MyModel):
    
    fileid = models.IntegerField(primary_key=True, verbose_name='ID')
    filename = models.CharField(max_length=500, verbose_name='Archivo')
    fileextension = models.CharField(max_length=50)
    filesize = models.IntegerField()
    filetype = models.CharField(max_length=100, verbose_name='Tipo')
    filedescription = models.CharField(max_length=500, verbose_name='Descripci' + mychr('o') + 'n')
    filesource = models.CharField(max_length=2)
    filedata = models.BinaryField()
    fileURL = models.URLField(max_length=500)
    filepath = models.CharField(max_length=256)
    fileclass = models.CharField(max_length=50)
    filecategory = models.CharField(max_length=10)
    fileattributes = JSONField()
    alternatefileid = models.IntegerField()
    contractid = models.IntegerField()
    schoolid = models.IntegerField()
    schoolyear = models.SmallIntegerField()

    # File Manager instance
    objects = FileManager()
    
    def get_properties(self, altproperties={}):
        mydict = {
            'filedescription': self.filedescription or altproperties.get('filedescription'),
            'filecategory': self.filecategory or altproperties.get('filecategory'),
            'fileclass': self.fileclass or altproperties.get('fileclass'),
            'contractid': self.contractid or altproperties.get('contractid'),
            'schoolid': self.schoolid or altproperties.get('schoolid'),
            'schoolyear': self.schoolyear or altproperties.get('schoolyear') 
        }

        for field in ('programname', 'userid', 'gd_locator'):
            myvalue = (self.fileattributes or {}).get(field)
            
            if myvalue:
                mydict[field] = myvalue
                
        return mydict
    
class Category(MyModel):
    
    categoryclass = models.CharField(max_length=50)
    categorytype = models.CharField(max_length=25)
    categorydisplayname = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    
    objects = CategoryManager()

wakemeup/templates/wakemeup/admin/create_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Crear usuario{% endblock %}

{% block content %}
	<div class="container-fluid">
		<br>
		<form method="POST" enctype="multipart/form-data" novalidate id="myform" 
			data-classes-url="{% url 'wakemeup:ajax_load_classes' %}" 
		>
		    {% csrf_token %}
			{% crispy form %}
		</form>
	</div>
{% endblock %}

{% block bodyimport %}
<script>

	// VALIDATION: Check e-mail and password fields
	function validate_form() {
		var warningmsg = ''
		
		var username = $("#id_username").val()
		var emailaddress = $("#id_emailaddress").val()
		var password = $("#id_password1").val()
		
		if(!password) {
			warningmsg += "No se especific&#243; una contrase&#241;a.  Se generar&#225; una contrase&#241;a aleatoria.<br><br>"
		}

		if(!emailaddress && !validateEmail(username)) {
			warningmsg += "No se especific&#243; un correo.  Por favor guarde los datos de usuario en la siguiente pagina para entregar al usuario.<br><br>"
		}
		
		if(warningmsg != '') {
			warningmsg = "<strong>Aviso</strong><br>" + warningmsg
		}
		
		return warningmsg
	};

	function validateEmail(email) 
	{
	    var re = /\S+@\S+\.\S+/;
	    return re.test(email);
	}
	
	// VALIDATION: Submit button listener
	$("#next").click(function(event) {
		validationresults = validate_form()
		if(validationresults != '') {
			bootbox_confirm('myform', validationresults)
		}
	})

	// VALIDATION: Submit button listener
	$("#id_schoolid").change(function(event) {
		update_classes()
	})

	// DROP-DOWNS: Update classes
	function update_classes() {
		// Get values from the form
	    var url = $("#myform").attr("data-classes-url");
	    var teacherUserId = $("#id_teacheruserid").val();
	    var schoolId = $("#id_schoolid").val();

	    $.ajax({
	      url: url,
	      data: {
	        'teacheruserid': teacherUserId,
	        'schoolid': schoolId,
	      },
	      success: function (data) {
	        $("#id_classid").html(data);
	      }
	    })
	};
	
	// DOCUMENT READY: Initialize
	$(document).ready(function(){
		update_classes();
	});
</script>
{% endblock %}

wakemeup/templates/wakemeup/admin/create_user_confirmation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Crear usuario - Resumen{% endblock %}

{% block content %}
	<div class="container-fluid">
		<legend>Crear Usuario - Revisar</legend>
		<div class="row">
			<div class="col col-sm-4"><strong>Nombre de usuario</strong></div>
			<div class="col col-sm-8">{{ userinfo.username }}</div>
		</div>
		<div class="row">
			<div class="col col-sm-4"><strong>Contrase&#241;a</strong></div>
			<div class="col col-sm-8">
				{% if conf_password_display %}
					{{ conf_password_display }}
				{% else %}
					******
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col col-sm-4"><strong>Nombre(s)</strong></div>
			<div class="col col-sm-8">{{ userinfo.firstname }}</div>
		</div>
		<div class="row">
			<div class="col col-sm-4"><strong>Apellido(s)</strong></div>
			<div class="col col-sm-8">{{ userinfo.lastname }}</div>
		</div>
		<div class="row">
			<div class="col col-sm-4"><strong>Correo</strong></div>
			<div class="col col-sm-8">{{ userinfo.emailaddress }}</div>
		</div><br>
		<i>
		{% if userinfo.emailaddress %}
		Se envi&#243; un correo a <strong>{{ userinfo.emailaddress }}</strong> con los datos.
		{% else %}
		Ya que no se provey&#243; un correo, por favor guarde los datos.
		{% endif %}
		</i>
		<br><br>
   		<a href="{% url 'wakemeup:create_user' %}" class="btn btn-primary">Crear otra</a>
   		<a href="{% url 'wakemeup:index' %}" class="btn btn-primary">Inicio</a>
	</div>
{% endblock %}

wakemeup/templates/wakemeup/admin/edit_class.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Admin - Cursos{% endblock %}

{% block content %}
	<div class="container-fluid">
		<br>
		<form method="POST" enctype="multipart/form-data" novalidate>
		    {% csrf_token %}
			{% crispy form %}
		</form>
	</div>
	
{% endblock %}

{% block bodyimport %}
	<script src="{% static 'wakemeup/js/editusergroup.js' %}"></script>
	
	<script>

		// MODAL - HIDE
		$('#editUserGroupModal').on('hidden.bs.modal', function (e) {
			document.getElementById("editUserGroupForm").reset();
		})	
	
		// MODAL - SUBMIT FORM
		$("#editUserGroupForm").submit(function(e) {
			update_usergroupform()
			return false // Ignore default submit behavior
		});

		$(document).ready(function(){
			// SHOW MODAL - EDIT
		    $('[name=submit_usergroup]').click(function() {
				var groupuserid = $(this.form).find('input[name=groupuserid]').val()
				var classid = $(this.form).find('input[name=classid]').val()
				
				// Populate and show modal
	            $("#mymodaldiv").html(""); // Clear modal div of any previous contents
				update_usergroupform("new", groupuserid, classid) // Update modal with new form
	        	$('#editUserGroupModal').modal("show");
		    });

			// SHOW MODAL - ADD NEW
		    $('#add_usergroup').click(function() {
				var classid = $("#classid").val();

				// Populate and show modal
	            $("#mymodaldiv").html(""); // Clear modal div of any previous contents
				update_usergroupform("new", classid) // Update modal with new form
	        	$('#editUserGroupModal').modal("show");
		    });
		});
	</script>
{% endblock %}

wakemeup/templates/wakemeup/admin/edit_inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>
<div class="table-responsive">
	{% with field_center_list="" %}
	    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table table-striped table-condensed">
        <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th for="{{ field.auto_id }}" class="control-label {% if field.field.required %}requiredField{% endif %} {% if field.name in field_center_list %}text-center{% endif %}">
                                {{ field.label|safe }}
                                {% if field.field.required and not field|is_checkbox %}<span class="asteriskField"></span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endif %}
        </thead>

        <tbody>
            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "bootstrap3/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                    	{% if field.field.widget.attrs.textonly %}
                    		<div class="form-group">
                    			<td style="vertical-align:middle" nowrap>
                    				<div class="controls">{{ field.value }}</div>
                   				</td>
               				</div>
                   		{% else %}
	                        {% include 'bootstrap3/field.html' with tag="td" form_show_labels=False %}
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
	{% endwith %}
</div>
    {% include "bootstrap3/inputs.html" %}

{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

wakemeup/templates/wakemeup/admin/edit_permissions.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

<!-- Set page title -->
{% block title %}Permisos{% endblock %}

{% block headimport %}
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<br>
	<form method="POST" enctype="multipart/form-data" action="{% url 'wakemeup:edit_permissions' %}" novalidate>
		<div class="container-fluid">
			<!-- Nav tabs -->
			<ul class="nav nav-tabs nav-tabs-sticky">
			  <li class="nav-item">
			    <a class="nav-link active" data-toggle="tab" href="#general">Archivos</a>
			  </li>
			</ul>
			
				<!-- Tab panes -->
			    {% csrf_token %}
				<div class="tab-content">
					<br>
					  <div class="tab-pane active" id="general">
							{% crispy filepermissionform %}
					  </div>
				</div>
			<br>
			<input type="submit" class="btn btn-primary" name="submit" value="Enviar"/>
			<input type="submit" class="btn btn-secondary" name="cancel" value="Cancelar"/>
		</div
	</form>
{% endblock %}

{% block bodyimport %}

	<!-- Javascript to maintain tab positioning -->
	<script src="{% static 'js/jquery.stickytabs.js' %}"></script>
	
	<script>
		$(document).ready(function() {
			$('.nav-tabs-sticky').stickyTabs();
		});
	</script>
{% endblock %}

wakemeup/templates/wakemeup/admin/edit_school.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

<!-- Set page title -->
{% block title %}Inicio{% endblock %}

{% block headimport %}
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<br>
	<form method="POST" enctype="multipart/form-data" action="{% url 'wakemeup:edit_object' objecttype='school' objectid=value %}" novalidate>
		<div class="container-fluid">
			<!-- Nav tabs -->
			<ul class="nav nav-tabs nav-tabs-sticky">
			  <li class="nav-item">
			    <a class="nav-link active" data-toggle="tab" href="#general">General</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#incentives">Incentivos</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#calendar">Calendario</a>
			  </li>
			</ul>
			
				<!-- Tab panes -->
			    {{ schoolrewardformset.management_form }}
			    {% csrf_token %}
				<div class="tab-content">
					<br>
					  <div class="tab-pane active" id="general">
							{% crispy form %}
					  </div>
					  <div class="tab-pane fade dcp-admin-form" id="incentives">
						{% crispy schoolrewardformset schoolrewardformset.form.helper %}
					  </div>
					  <div class="tab-pane fade" id="calendar">
						{% crispy calendarform %}
					  </div>
				</div>
			<br>
			<input type="submit" class="btn btn-primary" name="submit" value="Enviar"/>
			<input type="submit" class="btn btn-secondary" name="cancel" value="Cancelar"/>
		</div
	</form>
{% endblock %}

{% block bodyimport %}

	<!-- Javascript to maintain tab positioning -->
	<script src="{% static 'js/jquery.stickytabs.js' %}"></script>
	
	<script>
		$(document).ready(function() {
			$('.nav-tabs-sticky').stickyTabs();
		});
	</script>
{% endblock %}

wakemeup/templates/wakemeup/admin/edit_usergroup.html
{% load crispy_forms_tags %}
{% block content %}
	<div class="container-fluid">
		<br>
		{% crispy form %}
	</div>
{% endblock %}

wakemeup/templates/wakemeup/admin/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Admin{% endblock %}

{% block content %}
	<div class="container-fluid">
		<br>
		<form method="POST" enctype="multipart/form-data" novalidate>
		    {% csrf_token %}
			{% crispy form %}
		</form>
	</div>
{% endblock %}

wakemeup/templates/wakemeup/admin/index.html
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}

<!-- Set page title -->
{% block title %}{% if manageflag %}Admin - {% endif %}{{objectdisplayname}}{% endblock %}

{% block content %}
	<div class="container"><br>
		<div class="row">
			<div class="col">
				<div align="center">
					<h2>
						{{objectdisplayname}}
						{% if objecttype not in 'teacher student' %}
							{% if objecttype == "class" and request.user.usertype != "TR" or objecttype == "reward" %}
								{% if manageflag %}
									<div class="float-right">
										<a href="{% url 'wakemeup:edit_object' objecttype=objecttype objectid='new' %}">
											<i class="fas fa-plus-circle" style="font-size:1.125em;vertical-align:middle"></i>
										</a>
									</div>
								{% endif %}
							{% endif %}
						{% endif %}
					</h2>
				</div><div style="font-size:6px"><br></div>
			</div>
		</div>
		<div class="row d-flex justify-content-center">
			<div class="col">
				{% render_table objects %}
			</div>
		</div>
    </div>
{% endblock %}

wakemeup/templates/wakemeup/admin/profilepicture.html
{% load static %}
{% load crispy_forms_filters %}
{% load l10n %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors and field.errors %} has-danger{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

        {% if field.label %}
            <label for="{{ field.auto_id }}"  class="{{ label_class }}{% if not inline_class %} col-form-label{% endif %}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

		<div class="{% if inline_class %}form-check{% endif %}{% if field_class %} {{ field_class }}{% endif %}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>
		    {% include 'bootstrap4/layout/field_errors_block.html' %}
		
		    {% for choice in field.field.choices %}
		      {% if not inline_class %}<div class="form-check">{% endif %}
		        <label for="id_{{ field.id_for_label }}_{{ forloop.counter }}" class="form-check-{% if inline_class %}{{ inline_class }}{% else %}label{% endif %}">
					<div style="text-align:center">
						{% if choice.0 != 0 %}
			            	<img src="{% static 'img/avatar/'|add:choice.1|unlocalize %}" height="48px" width="48px"></img><br>&nbsp;
						{% else %}
	 						<i class="fas fa-user faicon" style="font-size:48px;height:48px;color:grey"></i><br>&nbsp;&nbsp;&nbsp;
						{% endif %}
			            <input 
			            	type="radio" 
			            	class="form-check-input"
			            	{% if choice.0|stringformat:"s" == field.value|default_if_none:""|stringformat:"s" %} checked="checked"{% endif %} 
			            	name="{{ field.html_name }}" 
			            	id="id_{{ field.id_for_label }}_{{ forloop.counter }}" 
			            	value="{{ choice.0|unlocalize }}" 
			            	{{ field.field.widget.attrs|flatatt }}
		            	>
	            	</div>&nbsp;
		        </label>
		      {% if not inline_class %}</div>{% endif %}
		    {% endfor %}
		
		    {% include 'bootstrap4/layout/help_text.html' %}
		</div>

    </div>
{% endif %}