dcp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from wakemeup.forms import LoginForm

urlpatterns = [
#     path('admin/', admin.site.urls),
    url('^wakemeup/', include('wakemeup.urls', namespace='wakemeup'), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view( # Catch login before default url
            template_name = 'registration/login.html', 
            authentication_form=LoginForm
        )
        , name="login"),
    url(r'^', include('django.contrib.auth.urls')), # Auth views (login, logout, reset password)
    url(r'^.*$', RedirectView.as_view(pattern_name='wakemeup:index')), # Redirect all other URLs to "Wake Me Up" homepage
]

wakemeup/urls.py
from django.conf.urls import url
from . import views

app_name = 'wakemeup' # qualifies url pattern names with 'wakemeup' namespace (i.e. 'wakemeup:create_contract')
urlpatterns = [

    # Index (i.e. /wakemeup)
    url(r'^$', views.index, name="index"),

    # Contract
    url(r'^contract/$', views.list_contract, name="list_contract"),
    url(r'^contract/(?P<contractid>(\d+))/detail$', views.get_contract, name="get_contract"),
    url(r'^contract/(?P<contractid>(\d+|new))$', views.create_contract, name="create_contract"),

    # Admin
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object"), # Object list
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))/(?P<objectid>\d+)$', views.edit_object, name="edit_object"), # Edit object
    url(r'^admin/(?P<objecttype>(school|class|reward))/(?P<objectid>new)$', views.edit_object, name="edit_object"), # New object
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward|contract))/(?P<objectid>\d+)/delete$', views.delete_object, name="delete_object"), # Delete object    

    # General
    url(r'^(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object_general"), # Object list (non-admin)

    url(r'^admin/tools$', views.execute_admintools, name="execute_admintools"),
    url(r'^admin/edit_permissions', views.edit_permissions, name="edit_permissions"),
    url(r'^admin/manage_program', views.manage_program, name="manage_program"),

    # User 
    url(r'^admin/create_user', views.create_user, name="create_user"),
    url(r'^myaccount', views.myaccount, name="myaccount"),

    # Calendar
    url(r'^calendar/', views.get_calendar, name='get_calendar'),

    # Files
    url(r'^files$', views.list_file, name="list_file"),
    url(r'^files/edit/(?P<fileid>(bulk))?$$', views.edit_file, name="edit_file_bulk"),
    url(r'^files/edit/(?P<fileid>(\d+|new))$', views.edit_file, name="edit_file"),
    url(r'^files/download/(?P<fileid>\d+)$', views.get_file, name='get_file'), # File download
    
    # Misc
    url(r'^admin/img/(?P<objecttype>(teacher))/(?P<objectid>\d+)/preview$', views.preview_image, name="preview_image"), # Image preview
    url(r'^about$', views.about, name='about'),
    url(r'^howtoparticipate$', views.howtoparticipate, name='howtoparticipate'),

    # Ajax
    url(r'^ajax/load-classes/', views.load_classes, name='ajax_load_classes'),
    url(r'^ajax/load-teachers/', views.load_teachers, name='ajax_load_teachers'),
    url(r'^ajax/load-rewards/', views.load_rewards, name='ajax_load_rewards'),
    
    url(r'^ajax/manage-user-display/', views.manage_user_display, name='ajax_manage_user_display'),
    url(r'^ajax/addreward/', views.addreward, name='ajax_add_reward'),

    # Default (catch all)    
    url(r'.*', views.index, name="default"),
]

user/models/base.py
from django.db import models

class MyModel(models.Model):

    class Meta:
        managed = False
        abstract = True
    
    def save(self, *args, **kwargs):
        return type(self).objects.save(self, *args, **kwargs)
    
    def delete(self):
        return type(self).objects.delete(self)

wakemeup/models/base.py
from django.db import models

class MyModel(models.Model):

    class Meta:
        managed = False
        abstract = True
    
    def save(self, *args, **kwargs):
        return type(self).objects.save(self, *args, **kwargs)
    
    def delete(self):
        return type(self).objects.delete(self)

class Object():
    pass

templates/base.html
<!-- Base template -->
{% load static %}
<!doctype html>
<html lang="en">
    <head>

        <!-- Meta info -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!--  IE support  -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="">
        <meta name="author" content="">

		<!-- Allow web app on Chrome -->
        <meta name="mobile-web-app-capable" content="yes">

		<!-- Import Jquery -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

		<!-- Backup local file -->
		<script>
		       window.jQuery || document.write('<script src="{% static 'js/jquery-3.5.1.min.js' %}"><\/script>');
		</script>

        <!-- Import Bootstrap core files  -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

		<!-- Import confirmation / alert box JS files -->
		<script src="{% static 'js/bootbox.min.js' %}"></script>
		<script src="{% static 'js/bootbox_common.js' %}"></script>

		<!-- Font Awesome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	    <!-- Custom CSS -->
	    <link href="{% static 'css/base.css' %}" rel="stylesheet">

        <!-- Page-specific imports -->
        {% block headimport %}{% endblock %}

        <!-- Workaround to allow styling of unknown HTML elements in IE browsers older than IE9 (must be after CSS imports) -->
        <!--[if lt IE 9]>
            <script src="{% static 'js/html5shiv.js' %}"></script>
        <![endif]-->

        <!-- Page title -->
        <title class="title">
            DCP - {% block title %}Inicio{% endblock %}
        </title>    

		<!-- realfavicongenerator.net -->
        <!-- Image to use for favorite/bookmark icon -->
{% comment %}        <link rel="icon" sizes="192x192" href="{% static 'img/logo/android-icon-96x96.png' %}" />{% endcomment %}
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/logo/favicon/apple-touch-icon.png?v=5ABpOj04rk' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/logo/favicon/favicon-32x32.png?v=5ABpOj04rk' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/logo/favicon/favicon-16x16.png?v=5ABpOj04rk' %}">
		<link rel="manifest" href="{% static 'img/logo/favicon/site.webmanifest?v=5ABpOj04rk' %}">
		<link rel="mask-icon" href="{% static 'img/logo/favicon/safari-pinned-tab.svg?v=5ABpOj04rk' %}" color="#5bbad5">
		<link rel="shortcut icon" href="/favicon.ico?v=5ABpOj04rk">
		<meta name="apple-mobile-web-app-title" content="DCP">
		<meta name="application-name" content="DCP">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">
    </head>

    {% block body %}
        <body>
            {% include "header.html" %}
            {% include "navbar.html" %}
            <main>
                <div class="container-fluid">
                    {% block content %}{% endblock %}
                </div>
            </main>
            {% include "footer.html" %}

			<!-- Navbar import -->
			<script src="{% static 'js/navinbox.js' %}"></script>
			
	        <!-- Page-specific imports -->
	        {% block bodyimport %}{% endblock %}
        </body>
    {% endblock %}
</html>

templates/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      {% autoescape off %}<span class="helptext">{{ field.help_text }}</span>{% endautoescape %}
    {% endif %}
  </div>
{% endfor %}

templates/footer.html
<footer class="footer">
	<div class="container">
		<span class="text-muted"><center>&copy; {% now "Y" %} Duitama Colegio Project</center></span>
	</div>
</footer>

templates/header.html
<header></header>

templates/link_post.html
<form id="{{formname}}" method="post" action="{{actionurl}}">{% csrf_token %}
	{% for key, value in fields.items %}
		<input type="hidden" name="{{key}}" value="{{value}}"/>
	{% endfor %}
	
	<a {% if displaytype == "navbar" %}class="dropdown-item {% if urlname == formurlname %} active {% endif %}" {% endif %} onclick="document.forms['{{formname}}'].submit();" style="cursor: pointer;">{{linktext}}</a>
</form>

templates/navbar.html
{% load static %}
{% load navigation %}
{% with url_name=request.resolver_match.url_name %}

<nav class="navbar navbar-expand-md bg-light navbar-light sticky-top">

	<!-- LOGO -->
	<a class="navbar-brand" href="{% url 'wakemeup:index' %}" title="Inicio">
<!--		<i class="fas fa-home faicon" style="color:grey"></i>-->
	<img src="{% static 'img/logo/home_icon.png' %}" style="width:55px">
	</a>
	
	<!-- NAVBAR TOGGLE ICON -->
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>

	<!--  COLLAPSIBLE ITEMS -->		
	<div class="collapse navbar-collapse" id="collapsibleNavbar">
		<ul class="nav navbar-nav mr-auto">
			{% if user.is_authenticated %}
			
				<!-- CONTRACTS -->
				{% if not auth.navbar.contracts.disable and auth.objects.contract.accesslevel >= 4 %}
					<li class="nav-item dropdown">				
						<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Contratos</a>
						<div class="dropdown-menu">
							{% if auth.objects.contract.accesslevel >= 10 %}
								<a class="dropdown-item {% if url_name == 'create_contract' %} active {% endif %}" href="{% url 'wakemeup:create_contract' contractid='new' %}">Crear contrato</a>
							{% endif %}
							<a class="dropdown-item {% if url_name == 'list_contract' %} active {% endif %}" href="{% url 'wakemeup:list_contract' %}">Mis contratos</a>
						</div>
					</li>
				{% endif %}

				<!-- CALENDAR -->
				{% if not auth.navbar.calendar.disable and auth.objects.calendar.accesslevel >= 4 %}
				<li class="nav-item dropdown">
					<a class="nav-link" href="{% url 'wakemeup:get_calendar' %}">Calendario</a>
				</li>
				{% endif %}
				
				<!-- REWARDS -->
				{% if not auth.navbar.reward.disable and auth.objects.reward.accesslevel >= 1 %}
				<li class="nav-item dropdown">
					<a class="nav-link" href="{% url 'wakemeup:list_object_general' objecttype='reward' %}">Incentivos</a>
				</li>
				{% endif %}
				
				<!-- FILES -->
				{% if not auth.navbar.files.disable and auth.objects.file.accesslevel >= 4 %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Archivos</a>
					<div class="dropdown-menu">
						{% if not auth.navbar.files.general.disable %}
	{% comment %}						<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'contract' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=contract">Contratos</a>{% endcomment %}
							<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'document' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=document">Documentos</a>
							<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'interview' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=interview">Entrevistas</a>
							<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'form' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=form">Formularios</a>
							<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'report' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=report">Informes</a>
							<a class="dropdown-item {% if url_name == 'list_file' and request.GET.filetype == 'video' %} active {% endif %}" href="{% url 'wakemeup:list_file' %}?filetype=video">Videos</a>
							<div class="dropdown-divider"></div>
						{% endif %}
						{% if not auth.navbar.files.explorer.disable %}
							<a class="dropdown-item {% if url_name == 'list_file' and not request.GET.filetype %} active {% endif %}" href="{% url 'wakemeup:list_file' %}">Explorador de archivos</a>
						{% endif %}
						{% if auth.objects.file.accesslevel >= 10 %}
							{% if not auth.navbar.files.manage.disable or not auth.navbar.files.upload.disable %}
								{% if not auth.navbar.files.explorer.disable %}
									<div class="dropdown-divider"></div>
								{% endif %}
							{% endif %}
							{% if not auth.navbar.files.upload.disable %}
								{% url 'wakemeup:edit_file' fileid='new' as actionurl %}
								{% link_post navcontext=navigation formname="edit_file" actionurl=actionurl displaytype="navbar" urlname=url_name linktext="Subir" %}
							{% endif %}
							{% if not auth.navbar.files.manage.disable %}
								{% url 'wakemeup:edit_file_bulk' as actionurl %}
								{% link_post navcontext=navigation formname="edit_file_bulk" actionurl=actionurl displaytype="navbar" urlname=url_name linktext="Gestionar" %}
							{% endif %}
						{% endif %}
					</div>
				</li>
				{% endif %}
				
				<!-- HOW TO PARTICIPATE -->
				<li class="nav-item dropdown">
					<a class="nav-link" href="{% url 'wakemeup:howtoparticipate' %}">C&oacute;mo participar</a>
				</li>
				
				<!-- ADMIN -->
				{% if not auth.navbar.admin.disable %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Admin</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{% url 'wakemeup:list_object' objecttype='school' %}">Colegios</a>
							<a class="dropdown-item" href="{% url 'wakemeup:list_object' objecttype='class' %}">Cursos</a>
							<a class="dropdown-item" href="{% url 'wakemeup:list_object' objecttype='teacher' %}">Docentes</a>
							<a class="dropdown-item" href="{% url 'wakemeup:list_object' objecttype='reward' %}">Incentivos</a>
							<div class="dropdown-divider"></div>
							
							{% if auth.objects.user.accesslevel >= 10 %}
								<a class="dropdown-item {% if url_name == 'create_user' %} active {% endif %}" href="{% url 'wakemeup:create_user' %}">Crear usuario</a>
							{% endif %}
							
							{% if auth.objects.program.accesslevel >= 10 %}
								<a class="dropdown-item {% if url_name == 'manage_program' %} active {% endif %}" href="{% url 'wakemeup:manage_program' %}">Programas</a>
							{% endif %}
							
							<!-- Permissions -->
							{% if not auth.navbar.admin.permissions.disable and auth.objects.permissions.accesslevel >= 8%}
								{% url 'wakemeup:edit_permissions' as actionurl %}
								{% link_post navcontext=navigation formname="edit_permissions" actionurl=actionurl displaytype="navbar" urlname=url_name linktext="Permisos" %}
							{% endif %}
							
							<!-- Admin tools -->
							{% url 'wakemeup:execute_admintools' as actionurl %}
							{% link_post navcontext=navigation formname="execute_admintools" actionurl=actionurl displaytype="navbar" urlname=url_name linktext="Sincronizar con Google Drive" %}
						</div>
					</li>
				{% endif %}
			{% endif %}
			
			<!-- ABOUT -->
			<li class="nav-item dropdown">
				<a class="nav-link" href="{% url 'wakemeup:about' %}">Acerca de</a>
			</li>
		</ul>
		<ul class="nav navbar-nav">
			{% if user.is_authenticated %}
			
				<!-- REPUTATION -->
				{% if not auth.navbar.reputation.disable %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'wakemeup:myaccount' %}#reputation" id="ReputationValueLink" title="Reputaci&#243;n">
						<h4 style="display:inline;vertical-align:middle">{{ user.reputationvalue }}</h4>
						{% if userinfo.reputationvaluedelta != 0 %}
							<span style="vertical-align:top; background-color:red;color:white" class="badge" id="ReputationValueDelta">
								+{{ userinfo.reputationvaluedelta }}
							</span>
						{% endif %}
					</a>
				</li>
				{% endif %}
				
				<!--  NOTIFICATIONS -->
			{% if not auth.navbar.notifications.disable %}
				<li class="nav-item dropdown" id="NotificationInboxDropdown">
				
					<!-- Notifications - Inbox icon -->
					<a 
						class="btn nav-link float-left" 
						id="NotificationInboxIcon" 
						data-toggle="dropdown" 
						aria-haspopup="true" 
						aria-expanded="false"
						style="color:{% if userinfo.opennotificationsflag %}red{% endif %}" 
						title="Notificaciones"
					>
						<i class="fas fa-inbox faicon"></i>
					</a>

					<!--  Notifications - Drop-down menu -->
					<div 
						class="dropdown-menu scrollable-menu dropdown-menu-right" 
						aria-labelledby="dropdownMenuLink" 
						id="NotificationInboxItems"
					>
					</div>
				</li>
			{% endif %}

				<!-- PROFILE -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" title="{{ user.username }}">
						{% if userinfo.profilepicturefile %}
							<img src="{% static 'img/avatar/'|add:userinfo.profilepicturefile %}" alt="Avatar" height="32px" width="32px" style="display:inline-block">
						{% else %}
	 						<i class="fas fa-user faicon"></i>
						{% endif %}
					</a>	
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="{% url 'wakemeup:myaccount' %}#profile">Mi cuenta</a>
						<a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesi&#243;n</a>
					</div>
				</li>
			{% else %}
			
				<!-- LOGIN -->
				<li class="nav-item">
					<a class="nav-link" href="{% url 'login' %}?next={% firstof request.path '/' %}">Iniciar sesi&#243;n</a>
				</li>
			{% endif %}
		</ul>
	</div>
</nav>
{% endwith %}