dcp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from wakemeup.forms import LoginForm

urlpatterns = [
#     path('admin/', admin.site.urls),
    url('^wakemeup/', include('wakemeup.urls', namespace='wakemeup'), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view( # Catch login before default url
            template_name = 'registration/login.html', 
            authentication_form=LoginForm
        )
        , name="login"),
    url(r'^', include('django.contrib.auth.urls')), # Auth views (login, logout, reset password)
    url(r'^.*$', RedirectView.as_view(pattern_name='wakemeup:index')), # Redirect all other URLs to "Wake Me Up" homepage
]

wakemeup/urls.py
from django.conf.urls import url
from . import views

app_name = 'wakemeup' # qualifies url pattern names with 'wakemeup' namespace (i.e. 'wakemeup:create_contract')
urlpatterns = [

    # Index (i.e. /wakemeup)
    url(r'^$', views.index, name="index"),

    # Contract
    url(r'^contract/$', views.list_contract, name="list_contract"),
    url(r'^contract/(?P<contractid>(\d+))/detail$', views.get_contract, name="get_contract"),
    url(r'^contract/(?P<contractid>(\d+|new))$', views.create_contract, name="create_contract"),

    # Admin
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object"), # Object list
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward))/(?P<objectid>\d+)$', views.edit_object, name="edit_object"), # Edit object
    url(r'^admin/(?P<objecttype>(school|class|reward))/(?P<objectid>new)$', views.edit_object, name="edit_object"), # New object
    url(r'^admin/(?P<objecttype>(school|class|teacher|reward|contract))/(?P<objectid>\d+)/delete$', views.delete_object, name="delete_object"), # Delete object    

    # General
    url(r'^(?P<objecttype>(school|class|teacher|reward))(/)?$', views.list_object, name="list_object_general"), # Object list (non-admin)

    url(r'^admin/tools$', views.execute_admintools, name="execute_admintools"),
    url(r'^admin/edit_permissions', views.edit_permissions, name="edit_permissions"),
    url(r'^admin/manage_program', views.manage_program, name="manage_program"),

    # User 
    url(r'^admin/create_user', views.create_user, name="create_user"),
    url(r'^myaccount', views.myaccount, name="myaccount"),

    # Calendar
    url(r'^calendar/', views.get_calendar, name='get_calendar'),

    # Files
    url(r'^files$', views.list_file, name="list_file"),
    url(r'^files/edit/(?P<fileid>(bulk))?$$', views.edit_file, name="edit_file_bulk"),
    url(r'^files/edit/(?P<fileid>(\d+|new))$', views.edit_file, name="edit_file"),
    url(r'^files/download/(?P<fileid>\d+)$', views.get_file, name='get_file'), # File download
    
    # Misc
    url(r'^admin/img/(?P<objecttype>(teacher))/(?P<objectid>\d+)/preview$', views.preview_image, name="preview_image"), # Image preview
    url(r'^about$', views.about, name='about'),
    url(r'^howtoparticipate$', views.howtoparticipate, name='howtoparticipate'),

    # Ajax
    url(r'^ajax/load-classes/', views.load_classes, name='ajax_load_classes'),
    url(r'^ajax/load-teachers/', views.load_teachers, name='ajax_load_teachers'),
    url(r'^ajax/load-rewards/', views.load_rewards, name='ajax_load_rewards'),
    
    url(r'^ajax/manage-user-display/', views.manage_user_display, name='ajax_manage_user_display'),
    url(r'^ajax/addreward/', views.addreward, name='ajax_add_reward'),

    # Default (catch all)    
    url(r'.*', views.index, name="default"),
]

wakemeup/models/base.py
from django.db import models

class MyModel(models.Model):

    class Meta:
        managed = False
        abstract = True
    
    def save(self, *args, **kwargs):
        return type(self).objects.save(self, *args, **kwargs)
    
    def delete(self):
        return type(self).objects.delete(self)

class Object():
    pass

wakemeup/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse
from django.core.validators import validate_email
from django.core.mail import send_mail
from django.forms.models import formset_factory

from lib.UsefulFunctions.imgUtils import renderImageFromDb
from lib.UsefulFunctions.dateUtils import *
from lib.UsefulFunctions.dataUtils import *
from lib.UsefulFunctions.httpUtils import *
from lib.UsefulFunctions.miscUtils import get_school_year
from lib.UsefulFunctions.stringUtils import *
from lib.UsefulFunctions.fileUtils import get_file_name_info
from lib.UsefulFunctions.googleUtils import GoogleDrive, GoogleCalendar

from django_tables2 import RequestConfig

import psycopg2
import re

from wakemeup.tables import *
from wakemeup.forms import *
from wakemeup.models.school import *
from wakemeup.models.program import *
from wakemeup.models.environment import *
from user.models.user import UserReputationEvent, UserBadge, UserNotification
from user.models.authorization import *

DEFAULT_SCHOOL_YEAR = get_school_year()

# Check authentication (logged in)
def check_authentication(view):
    
    def view_wrapper(*args, **kwargs):
        myuser = args[0].user

        # Check user is logged on
        if myuser.is_authenticated:
            return view(*args, **kwargs)
        else:
            return redirect('login')
        
    return view_wrapper

# Check authorization (logged in & permissions)
def check_authorization(view):
    
    def view_wrapper(*args, **kwargs):
        myuser = args[0].user

        # Check user is logged on
        if myuser.is_authenticated:
            
            # Parse out view info
            viewname = view.__name__ # i.e. "create_contract"
            viewname_split = viewname.split("_")
            
            # Get action & object
            view_action = viewname_split[0]
            view_object = viewname_split[1] if len(viewname_split) > 1 else None # Use second index of view name (if specified)
    
            # Convert to access levels
            if view_action == "list":
                myrequestedaccesslevel = 1
                
            elif view_action == "get":
                myrequestedaccesslevel = 4
                
            elif view_action in ("edit", "execute"):
                if kwargs.get('objectid') == "new":
                    myrequestedaccesslevel = 10 # Create
                else:
                    myrequestedaccesslevel = 8 # Edit
                    
            elif view_action in ("create", "manage"):
                myrequestedaccesslevel = 10
                
            elif view_action == "delete":
                myrequestedaccesslevel = 12
                
            else:
                myrequestedaccesslevel = 1 # Browse
            
            # Get object
            if view_action in ('list','get','edit','create','execute','delete','manage'):
                myobject = Object.objects.get_object_by_name(objectname=kwargs.get('objecttype') or view_object) # business object
            else:
                myobject = Object.objects.get_object_by_name(objectname=viewname) # view

            # Check valid object
            if myobject:

                # Check user has requested access to object
                if myuser.check_access(objectid=myobject.objectid, objectclass=myobject.objectclass, requestedaccesslevel=myrequestedaccesslevel):

                    # Valid permission - continue
                    return view(*args, **kwargs)
        else:
            # Not authenticated - redirect to login page
            return redirect(reverse('login') + '?next={0}'.format(args[0].get_full_path_info()))
        
        # Not authorized - redirect to homepage (TO-DO: Create "not authorized" page)
        return redirect_home()

    # Return view
    return view_wrapper

# Get relative root directory for files
def get_rootdir(request, gd_locator, programname='incentive', ignoreadminflag=False, **kwargs): # TO-DO: Fix hardcoded
    if (request.user.is_admin() and not ignoreadminflag):
        gd_locator = get_gd_locator('programs_base')
        programname = None
        
    return File.objects.lookup_fileid_gd(gd_locator=gd_locator, programname=programname, **kwargs)

# Check if form is being saved
def check_saveform(request):
    return True if request.method == "POST" and not request.POST.get('source') else False

# AJAX Request handler
def load_teachers(request):
    contractid = request.GET.get('contractid') # Check if existing contract

    # Determine which teachers to display
    # If existing contract, use contract teacheruserid
    if(contractid):
        teacheruserid = Contract.objects.get(contractid=contractid).teacheruserid
    # If logged on user is a teacher teacheruserid
    elif(request.user.usertype == 'TR'):
        teacheruserid = request.user.userid
    # Otherwise, return all teachers
    else:
        teacheruserid = None
    
    # Lookup teacher classes
    teachers = Teacher.objects.get_teachers(teacheruserid = teacheruserid)
    
    return render(request, 'wakemeup/admin/menus/teacher_options.html', {'teachers': teachers, 'teacheruserid':teacheruserid})

def load_classes(request):
    contractid = request.GET.get('contractid') # Check for existing contract
    schoolid = request.GET.get('schoolid') # Check for existing school
    teacheruserid = request.GET.get('teacheruserid') # Check selected teacher

    classid = None

    # If existing contract, use existing data
    if(contractid):
        mycontract = Contract.objects.get(contractid=contractid)
        classid = mycontract.classid
        teacheruserid = mycontract.teacheruserid

        classes = Class.objects.get_classes(classid=classid, teacheruserid = teacheruserid)
        
    elif(schoolid):
        classes = Class.objects.get_classes(schoolid=schoolid)
        
    # Lookup teacher classes
    elif (teacheruserid):
        
        # If id = 0, include all teachers (used for add user form)
        if str(teacheruserid) == "0":
            teacheruserid = None
            
        classes = Class.objects.get_classes(teacheruserid = teacheruserid)
        
    else:
        classes = [] # Return empty list (create contract form)

    return render(request, 'wakemeup/admin/menus/class_options.html', {'classes': classes, 'classid': classid})

def load_rewards(request):
    contractid = request.GET.get('contractid') # Check if existing contract
    userid = request.user.userid

    # Get all existing rewards for given goal
    if(contractid):
        selectedrewards = ContractPartyReward.objects.get_contract_party_rewards(contractid=contractid)        
        selectedrewards = [myreward.rewardid for myreward in selectedrewards]
        
    else:
        selectedrewards = []

    context = {
        'selectedrewards': selectedrewards
    }
    
    return render(request, 'wakemeup/admin//reward_options.html', context)

@check_authorization
def execute_admintools(request):

    # Handle link redirect
    if check_saveform(request):
        action = request.POST.get('action')
        
        if action == "drivesync":
            gd = GoogleDrive()
            gd.sync()
            
    return HttpResponse("Success")

def manage_user_display(request):
    actiontype = request.GET.get('actiontype') # Check if existing contract

    # Load notifications
    if(actiontype == 'loadnotifications'):
        mynotifications = UserNotification.objects.get_notifications(userid=request.user.userid,activeonlyflag=False,maxrows=10)

        return render(request, 'wakemeup/notifications.html', {'usernotifications': mynotifications})

    # Set notifications as "seen"
    elif(actiontype == "clearusernotifications"):
        notificationtype = request.GET.get('notificationtype')
        get_user_model()(userid=request.user.userid).manage_display_info(actiontype='clearusernotifications',notificationtype=notificationtype)
        
    # Set notifications as "seen"
    elif(actiontype == "clearnewrepnotification"):
        get_user_model()(userid=request.user.userid).manage_display_info(actiontype='clearnewrepnotification')
        
    return HttpResponse()

# View to display images from DB
def preview_image(request, objecttype, objectid):
    if(objecttype == 'teacher'):
        img = Teacher.objects.get(objectid).defaultsignaturescanfile

    if(img):
        return renderImageFromDb(img)
    else:
        return HttpResponse()

def redirect_home():
    return redirect('wakemeup:index')        

def redirect_referer(request):
    return redirect(request.META['HTTP_REFERER']) if request.META.get('HTTP_REFERER') else redirect_home()

@check_authorization
def delete_object(request, objecttype, objectid):
    
    # Set default redirect
    if(objecttype == 'contract'):        
        myredirect = redirect('wakemeup:list_contract')
    else:
        myredirect = redirect('wakemeup:list_object', objecttype = objecttype)
        
    if(request.method == 'POST'):
        if(objecttype == 'contract'):
            myobject = Contract.objects.get(objectid)

            # Send notification when deleting non-draft contracts
            if myobject.contractstatus != 'D':
                sendnotifications = True
            else:
                sendnotifications = False

            # Delete contract
            myobject.delete(sendnotifications=sendnotifications)

            # Send notifications
            if(sendnotifications):
                myobject.send_emails(
                    email_subject = 'Duitama Colegio Project - Contrato (#' + str(myobject.contractid) + ') ha sido eliminado',
                    email_body = 'Se elimin' + mychr('o') + ' su contrato (#' + str(myobject.contractid) + ')'
                )
        else:

            if(objecttype == 'school'):
                myobject = School.objects.get(objectid)
                

wakemeup/templates/wakemeup/about.html
{% extends "base.html" %}
{% load static %}

<!-- Set page title -->
{% block title %}Acerca de{% endblock %}

{% block content %}
	<div class="container-fluid infopage"><br>
		<div class="row">
			<div class="col text-center">
				<img src="{% static 'img/logo/logo_incentives.png' %}" style="width:90%;max-width:400px">
			</div>
		</div><br>
		<div class="row">
			<div class="col">
			{% comment %}
				<img src="{% static 'img/logo/logo_incentives.png' %}" class="pull-left img-responsive" style="width:100%;max-width:300px">
			{% endcomment %}
				<div>
					Este programa dispondr&#225; de un sistema de incentivos para motivar a los estudiantes a desempe&#241;ar bien sus tareas en la clase de ingl&#233;s.  
					Estudiantes y docentes llegar&#225;n a un acuerdo sobre la estructura de los incentivos para lograr objetivos espec&#237;ficos de la clase, que 
					luego se formalizar&#225;n en un acuerdo escrito.  Si los estudiantes logran sus objetivos, recibir&#225;n sus incentivos.
				</div><br>
		
				<legend>Metas</legend>
				<div>
					La meta principal es mejorar los niveles estudiantiles de motivaci&#243;n por medio de una din&aacute;mica diferente.  Tambi&#233;n debe inculcar estos valores:<br><br>
					<ul>
						<li><strong>Respeto</strong> a las reglas del acuerdo</li>
						<li><strong>Puntualidad</strong> en adherir a las fechas tope del acuerdo</li>
						<li><strong>&#201;tica de trabajo</strong> para lograr los objetivos</li>
						<li><strong>Confianza</strong> en que ser&#225;n recompensados por sus esfuerzos</li>
					</ul>
				</div>
		
				<legend>Duitama Colegio Project</legend>
				<div>
					Este proyecto fue inspirado por una canci&#243;n del grupo de m&#250;sica Avicii, llamada "The Nights."  La canci&#243;n aconseja explorar este mundo, 
					seguir tu coraz&#243;n, perseguir las cosas importantes para ti y no tomar por hecho esta vida.
				</div><br>
				
				<legend>Plataforma</legend>
				<div>
					Esta aplicaci&#243;n se ve mejor usando la &#250;ltima versi&#243;n de <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a> con JavaScript activado.<br>
				</div><br>
				
				<legend>Contacto</legend>
				<div>
					<a href="mailto:admin@duitamacolegioproject.org">admin@duitamacolegioproject.org</a>
				</div>
			</div>
		</div>
    </div>
{% endblock %}

wakemeup/templates/wakemeup/howtoparticipate.html
{% extends "base.html" %}
{% load static %}

<!-- Set page title -->
{% block title %}C&oacute;mo participar{% endblock %}

{% block headimport %}
<!-- ACCORDION: https://bootsnipp.com/snippets/O5D4q -->
	<script type="text/javascript">
		$(document).ready(function() {
			$('.panel-collapse').on('shown.bs.collapse', function (e) {
			    var $card = $(this).closest('.card');
			    $('html,body').animate({
			        scrollTop: $card.offset().top - 70
			    }, 400); 
			}); 
		});	
	</script>
	
	<style>
		.panel-group {
		    background: #fff none repeat scroll 0 0;
		    border-radius: 3px;
		    box-shadow: 0 5px 30px 0 rgba(0, 0, 0, 0.04);
		    margin-bottom: 0;
		    padding: 30px;
		}
		#accordion .card {
		    border: medium none;
		    border-radius: 0;
		    box-shadow: none;
		    margin: 0 0 15px 10px;
		}
		#accordion .panel-heading {
		    border-radius: 30px;
		    padding: 0;
		}
		#accordion .panel-title a {
		    background: #ffb900 none repeat scroll 0 0;
		    border: 1px solid transparent;
		    border-radius: 30px;
		    color: #fff;
		    display: block;
		    font-size: 16px;
			font-weight: bold;
		    padding: 12px 20px 12px 50px;
		    position: relative;
		    transition: all 0.3s ease 0s;
		}
		#accordion .panel-title a.collapsed {
		    background: #fff none repeat scroll 0 0;
		    border: 1px solid #ddd;
		    color: #333;
		}
		#accordion .panel-title a::after, #accordion .panel-title a.collapsed::after {
		    background: #ffb900 none repeat scroll 0 0;
		    border: 1px solid transparent;
		    border-radius: 50%;
		    box-shadow: 0 3px 10px rgba(0, 0, 0, 0.58);
		    color: #fff;
		    content: "\f078";
		    font-family: fontawesome;
		    font-size: 15px;
		    height: 55px;
		    left: -20px;
		    line-height: 55px;
		    position: absolute;
		    text-align: center;
		    top: -5px;
		    transition: all 0.3s ease 0s;
		    width: 55px;
		}
		#accordion .panel-title a.collapsed::after {
		    background: #fff none repeat scroll 0 0;
		    border: 1px solid #ddd;
		    box-shadow: none;
		    color: #333;
		    content: "\f054";
		}
		#accordion .panel-body {
		    background: transparent none repeat scroll 0 0;
		    border-top: medium none;
		    padding: 20px 25px 10px 9px;
		    position: relative;
		}
		#accordion .panel-body p {
		    border-left: 1px dashed #8c8c8c;
		    padding-left: 25px;
		}
	</style>
{% endblock %}

{% block content %}
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title text-center"><br>
					<h2>C&oacute;mo participar</h2>
				</div>
			</div>
		</div>
		<div class="row d-flex flex-wrap align-items-center">
			<div class="col-md-12">
				{% if request.user.usertype == "ST" %}
					<div class="d-flex justify-content-center">Por favor consulte con su profe de ingl&eacute;s.</div>
				{% else %}
					<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
						<div class="card">
							<div class="panel-heading" role="tab" id="headingOne">
								<h4 class="panel-title">
									<a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
										Paso 1 - Revisar el presupuesto
									</a>
								</h4>
							</div>
							<div id="collapseOne" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
								<div class="panel-body">
									<p>
										Revisar el presupuesto y pagar la matr&iacute;cula acordada&nbsp; <a href="{% url 'wakemeup:get_calendar' %}" target="_blank"><img height="24" src="{% static 'img/icon/calendar.png' %}"></a>
									</p>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="panel-heading" role="tab" id="headingTwo">
								<h4 class="panel-title">
									<a class="collapsed" role="button" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
										Paso 2 - Preparar los acuerdos
									</a>
								</h4>
							</div>
							<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
								<div class="panel-body">
									<p>
										Descargar y rellenar el formulario del acuerdo de estudiante-docente&nbsp;
										{% if contractfileid %}
											<a href="{% url 'wakemeup:get_file' fileid=contractfileid %}?exporttype=pdf"><img height="24" src="https://drive-thirdparty.googleusercontent.com/128/type/application/pdf"/></a>&nbsp;
											<a href="{% url 'wakemeup:get_file' fileid=contractfileid %}?exporttype=docx"><img height="24" src="https://drive-thirdparty.googleusercontent.com/128/type/application/vnd.openxmlformats-officedocument.wordprocessingml.document"/></a>
										{% endif %}
									</p>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="panel-heading" role="tab" id="headingThree">
								<h4 class="panel-title">
									<a class="collapsed" role="button" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
										Paso 3 - Entregar los acuerdos
									</a>
								</h4>
							</div>
							<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
								<div class="panel-body">
									<p>
										Entregar los acuerdos con todos los detalles, incluso la lista de participantes <a href="{% url 'wakemeup:get_calendar' %}" target="_blank"><img height="24" src="{% static 'img/icon/calendar.png' %}"></a>
									</p>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="panel-heading" role="tab" id="headingFour">
								<h4 class="panel-title">
									<a class="collapsed" role="button" data-toggle="collapse" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
										Paso 4 - Entregar los resultados
									</a>
								</h4>
							</div>
							<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour" data-parent="#accordion">
								<div class="panel-body">
									<p>
										1. Evidencias (videos, fotos o archivos)<br>
										2. Lista de ganadores<br>
										3. Lista de incentivos seleccionados <a href="{% url 'wakemeup:get_calendar' %}" target="_blank"><img height="24" src="{% static 'img/icon/calendar.png' %}"></a><br>
									</p>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="panel-heading" role="tab" id="headingFive">
								<h4 class="panel-title">
									<a class="collapsed" role="button" data-toggle="collapse" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
										Paso 5 - Recibir los incentivos
									</a>
								</h4>
							</div>
							<div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive" data-parent="#accordion">
								<div class="panel-body" align="center">
									<p><img src="{% static 'img/incentive.png' %}" style="width:100%;max-width:300px"></p>
								</div>
							</div>
						</div>
						<div class="card">
							<div class="panel-heading" role="tab" id="headingSix">
								<h4 class="panel-title">
									<a class="collapsed" role="button" data-toggle="collapse" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
										C&oacute;mo enviar los archivos
									</a>
								</h4>
							</div>
							<div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix" data-parent="#accordion">
								<div class="panel-body">
									<p>
										Opci&oacute;n 1 - Por <a href="mailto:admin@duitamacolegioproject.org">correo electr&oacute;nico</a><br>
										Opci&oacute;n 2 - Por WhatsApp<br>
										Opci&oacute;n 3 - Por Google Drive (<i>admin@duitamacolegioproject.org</i>)
									</p>
								</div>
							</div>
						</div>
					</div>
				{% endif %}
			</div>	
		</div>		
	</div>
{% endblock %}

wakemeup/templates/wakemeup/index.html
{% extends "base.html" %}
{% load static %}

<!-- Set page title -->
{% block title %}Inicio{% endblock %}

{% block headimport %}
	<style>
		.btn-max-width {
		  margin-right: auto;
		  margin-left: auto;
		  max-width: 300px;
		}
	</style>
{% endblock %}

{% block content %}
	<div class="container">
		<br><br>
	    <div class="row btn-max-width">
    		<a href="{% url 'wakemeup:list_file' %}" class="btn btn-primary btn-lg btn-huge btn-block">Archivos</a>
	    </div>
	    <br>
	    <div class="row btn-max-width">
    		<a href="{% url 'wakemeup:get_calendar' %}" class="btn btn-primary btn-lg btn-huge btn-block">Calendario</a>
	    </div>
    </div>
{% endblock %}

wakemeup/templates/wakemeup/myaccount.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load render_table from django_tables2 %}

<!-- Set page title -->
{% block title %}Inicio{% endblock %}

{% block content %}
	<br>
	<div class="container-fluid">
		<!-- Nav tabs -->
		<ul class="nav nav-tabs nav-tabs-sticky">
		  <li class="nav-item">
		    <a class="nav-link active" data-toggle="tab" href="#profile">Perfil</a>
		  </li>
			{% if not auth.myaccount.reputation.disable %}
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#reputation">Reputaci&#243;n</a>
			  </li>
			{% endif %}
			{% if not auth.myaccount.badges.disable %}
			  <li class="nav-item" {% if auth.myaccount.badges.disable %}style="display:none"{% endif %}
			    <a class="nav-link" data-toggle="tab" href="#badges">Medallas</a>
			  </li>
			{% endif %}
			{% if not auth.myaccount.tools.disable %}
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#tools">Herramientas</a>
			  </li>
			{% endif %}
		</ul>
		
		<!-- Tab panes -->
		<div class="tab-content">
		<br>
		  <div class="tab-pane active" id="profile">
			<form method="POST" enctype="multipart/form-data" novalidate>
			    {% csrf_token %}
				{% crispy form %}
			</form>
		  </div>
			{% if not auth.myaccount.reputation.disable %}
		  <div class="tab-pane fade" id="reputation">
			{% render_table reputationevents %}
		  </div>
			{% endif %}
			{% if not auth.myaccount.badges.disable %}
		  <div class="tab-pane fade" id="badges">
			{% render_table badges %}
		  </div>
			{% endif %}
			{% if not auth.myaccount.tools.disable %}
		  <div class="tab-pane fade" id="tools">
			<a href="{% url 'password_reset' %}">Restablecer contrase&#241;a</a>
		  </div>
			{% endif %}
		</div>
    </div>
{% endblock %}

{% block bodyimport %}

	<!-- Javascript to maintain tab positioning -->
	<script src="{% static 'js/jquery.stickytabs.js' %}"></script>
	
	<script>
		$(document).ready(function() {
			$('.nav-tabs-sticky').stickyTabs();
		});
	</script>
{% endblock %}

wakemeup/templates/wakemeup/notifications.html
<div class="small">
	{% for notification in usernotifications %}
		<a 
			class="dropdown-item" 
			style="line-height:10px;{% if not notification.notificationseen %}font-weight:bold{% endif %}"
			href="
				{% if notification.eventclass == 'BD' %} 
					{% url 'wakemeup:myaccount' %}#badges 
				{% elif notification.eventclass == 'RP' %} 
					{% url 'wakemeup:myaccount' %}#reputation
				{% elif notification.eventclass == 'CT' %} 
					{% url 'wakemeup:get_contract' contractid=notification.contractid %}
				{% endif %}"
		>
			{{ notification.notificationtext }}
		</a>
		{% if not forloop.last %}
		 <div class="dropdown-divider"></div>
	 	{% endif %}
	{% endfor %}		
</div>